### ISSUE TITLE
Sweetalert 2 JS is not working properly in small devices

### ISSUE THREAD

**Issue by kishoredr** [sweetalert2/sweetalert2-examples#1]
Hello, I'm using a SweetAlert2 the alert popups, in the desktop version coming fine but in mobile/ small devices is not working properly

```
    Swal.fire({
                type: 'success',
                title:  response.data.body.Data[0].status_text,
                timer: 3500
             }) 

```

Desktop version:

![rcqzm](https://user-images.githubusercontent.com/5820212/53387239-f38ff700-39ab-11e9-9ee8-f270928904c0.png)

Mobile Version:
![vttzw](https://user-images.githubusercontent.com/5820212/53387254-099db780-39ac-11e9-9951-07ec6f15be0e.jpg)

How can I resolve this issue I spent more than a day for this.

Thanks in advance.

---

**Comment by gverni** [comment]
hi @kishoredr, could you please provide a feed-back as requested or close the issue if you have resolved it?

**Comment by badru123** [comment]
I have the same problem with this, I display the data with a table and add a sweet alert in the delete menu to confirm it, if the big screen works perfectly, but on the small screen only the data has 1 column running, but if there is data in it 2 columns or more sweet alerts do not appear and immediately delete data
