### ISSUE TITLE
Remove css from github.io in example pages

### ISSUE THREAD

**Issue by gverni** [sweetalert2/sweetalert2-examples#3]
When the browser window width is less than 1150px the `nav` elements in the side bar are not visible. 

You can see the element in the bar disappearing while shrinking the windows in [this video](https://www.useloom.com/share/48bb778f3d5c48dd88dbf50feceaac39). 

@limonte have you ever seen this? I reproduced it with chrome72 on both macOS and win10 using the example at https://sweetalert2.github.io/sweetalert2-examples/misc/side-panel/.

**Comment by limonte** [comment]
That's because we're fetching styles from https://sweetalert2.github.io/styles/styles.css

I think it would be better if `sweetlalert2-examples` would not rely on external styles.

**Comment by gverni** [comment]
Thanks @limonte and sorry about the false alarm! I definitely agree with
you. I'm working on restructuring the dependencies in the repo and i'll get
rid of that as well.
